namespace NiotechoneCQRS.Domain.Enum;

public class Enums
{
    public enum UserType
    {
        SGEAdmin = 1,
        TenentUser = 2,
        Requestor = 3,
        Admin = 4,
        Crew = 5,
        Client = 6,
        Supervisor = 7
    }

    public enum ArtifactType
    {
        CompanyHeader = 1,
        CompanyFooter = 2,
        FavImage = 3
    }

    public enum UserRole
    {
        SuperAdmin = 1
    }

    public enum ConfigMasterKey
    {
        Registration_ForgotPassword,
        Registration_ForgotPassword_Subject,
        Registration_NewUserCreated,
        Registration_NewUserCreated_Subject,
        Failure_MailAddress,
        Failure_MeterReading_Subject,
        Failure_MeterReading_Message,
        Expire_Certification_Subject,
        Expire_Certification_Message,
        Personnel_WorkOrderAllocation_Notification,
        Personnel_WorkOrderDeAllocation_Notification,
        WorkOrderAllocation_Subject,
        WorkOrderDeAllocation_Subject,
        //WorkOrder_Closed_Subject,
        //WorkOrder_Closed_Notification,
        WorkOrder_Invoice_Subject,
        WorkOrder_Invoice_Notification,
        WorkOrder_Quotation_Subject,
        WorkOrder_Quotation_Notification,
        WorkOrder_Status_Subject,
        WorkOrder_Status_Notification,
        WorkOrder_Quotation_Notification_For_Octopus,
        Escalation_Workorder,
        PurchaseRequest_Approved_Subject,
        PurchaseRequest_Approved_Notification,
        Inspection_Aesthetic_Report,
        Inspection_WorkOrder,
        WorkOrder_Checklist,
        WorkOrder_QuotationRequest,
        WorkOrder_QuotationRequest_Subject,
        WorkRequest_AssetIsMandatory,
        WorkOrder_CopyPriorityFromWorkRequestToWorkOrderDescription,
        WorkOrder_PersonnelIsMandatory,
        QRCode_Configuration,
        CustomLogo,
        InspectionReport_IssueDetail_Format,
        Scheduling_Personnel_TeamMember,
        FailureType_WorkOrder_Mandatory,
        WorkOrderType_WorkOrder_Mandatory,
        Asset_UserPermission_Configuration,
        AutoGenerateAssets,
        ShowEstimatedCostInInspectionReport,
        PPM_Alert_Subject,
        PPM_Alert_Message,
        PPM_Alert_EmailAddress,
        ShowEditWRCreatedDate,
        WorkRequest_Status_Subject,
        WorkRequest_Status_Notification,
        Enquiry_Status_Notification,
        ShowKPIModuleConfig,
        ShowContractsModuleConfig,
        Contract_Expiry_Subject,
        Contract_Expiry_Notification,
        Contract_Review_Subject,
        Contract_Review_Notification,
        Contract_Notice_Subject,
        Contract_Notice_Notification,
        Show_Client_Module_Config,
        Show_ClientContracts_ModuleConfig,
        Show_ClientAssets_ModuleConfig,
        Show_PersonnelSLA_ModuleConfig,
        Show_SubContractorContracts_Config,
        Show_Permission_For_Sales_Revenue,
        Contract_Status_Subject,
        Contract_Status_Notification,
        Contract_Create_Subject,
        Contract_Create_Notification,
        ShowOldAssetNoInAssetList,
        ImportExportAssetsInApscoFormat,
        ShowInspectionTypeInAssetModule,
        PPM_Status_Subject,
        PPM_Status_Notification,
        AssetTransferWO_Status_Notification,
        WorkOrder_Reminder_Subject,
        WorkOrder_Reminder_Notification,
        Service_Report_WRInfo,
        Service_Report_SPInfoWithoutCost,
        Service_Report_AssetInfo,
        Service_Report_WOInfo,
        Service_Report_SparePartsInfo,
        Service_Report_CrewInfo,
        Service_Report_WONotes,
        Service_Report_CustomerRemarks,
        Service_Report_ChecklistAndComments,
        Service_Report_WOImages,
        Service_Report_Template,
        Service_Report_ShowAllWorkOrderNotes,
        Service_Report_WOHistory,
        Subscription_Expiry_Subject,
        Subscription_Expiry_Notification,
        Subscription_Notify_Subject,
        Subscription_Notify_Notification,
        Enable_Anrie_Customization,
        Enable_NonInventory,
        SendServiceReportOnWOClosure,
        CaptureWorkOrderTravelTime,
        Enable_InventorySellingPrice,
        RecordPastWorkOrder,
        UpdateAssetInInspectionApp,
        Enable_Quotation,
        Enable_Invoicing,
        Quot_Invoice_PDF_Header,
        Quotation_PDF_Body,
        SalesQuotation_PDF_BODY,
        Estimation_PDF_Body,
        Invoice_PDF_Body,
        Link_Crew_To_All_Admins,
        Grant_Store_Access_To_All,
        Enable_QRCode_ForItems,
        Scan_Asset_QRCode_To_Update_WorkOrder_Progress,
        AutoGenerate_PPM_For_CurrentMonth,
        Generate_PPM_BasedOn_LastGenerated_PPM_Status,
        Show_column_to_review_workorder_planning_clashes,
        Grant_Permission_To_All_Users_While_Creating_WorkRequest_Type,
        Add_Work_Order_Type_Code,
        Generate_CBS_Code_In_Work_Order,
        Generate_ANREI_Work_Order_Reference_No,
        Current_No_For_WO_Ref_No,
        End_No_For_WO_Ref_No,
        WorkOrderUpdated_Status_Notification,
        PPMUpdated_Status_Notification,
        Edit_WR_ContactInfoDetails_By_Requestor,
        Add_OnHold_RequireSpareparts_Status,
        Email_Mobile_Notification,
        Show_Asset_Contract,
        Show_Contract_Asset,
        Add_OnHold_Client_Status,
        Add_Under_Observation_Status,
        Add_Client_Role,
        Sales_Module,
        Add_Supervisor_Role,
        Completed_WorkOrder_Cannot_Be_Changed_By_Crew,
        Enable_Geo_Fence_To_Validate_Location,
        Show_Completion_Form,
        PMCheckList_With_Frequency_Every,
        Quotation_Approval_Sub,
        Quotation_Approval_Body,
        View_Team_Location,
        Show_Custom_Logo,
        Show_ASFM_Report,
        Enable_BabirusIntegration,
        Zoho_Accumulated_Depreciation_Equipments,
        Zoho_Depreciation_Amortization_Direct,
        Show_PartnerSparePartId,
        Generate_PM_WorkOrders_For_Sunday_On_Monday,
        Generate_PM_WorkOrders_For_Friday_On_Saturday,
        Allow_Custom_WorkOrderStatus,
        Enable_RFID_labels_Export,
        Capture_Purchase_Order_Life_Cycle_Dates,
        Sales_Threshold,
        Create_Enquiry_From_WorkOrder,
        Enable_WorkOrder_Customization_Description_Wakhem,
        Record_Time_in_Days_and_Hours,
        Enable_Document_Upload_Validation_In_Enquiry,
        Sales_Module_Prefix_PrefixForQuotation,
        Sales_Module_Prefix_Enquiry_Current_Reference_No,
        Sales_Module_Prefix_Quotation_Current_Reference_No,
        Sales_Module_Prefix_PrefixForEnquiry,
        Show_callouts,
        Sales_Module_Prefix_PrefixForInvoice,
        Sales_Module_Prefix_Invoice_Current_Reference_No,
        Enable_StockInHandGreaterThanZero,
        Add_location_and_coordinates_to_work_order,
        InspectionWorkOrder_Status_Notification,
        AdditionalJobWorkOrder_Status_Notification,
        Invoicing_With_WorkOrder,
        SalesWOInvoice_PDF_BODY,
        WorkOrder_Invoice_PdF_Header,
        WOInvoice_Email_Subject,
        WOInvoice_Email_Body,
        Schedule_WorkOrder_In_BackDate,
        Automatically_Convert_WorkRequest_To_WorkOrder,
        Skip_Travel_Time_In_PM,
        Enable_Theme_Color_Customization,
        Enable_Company_Header_And_Footer,
        Enable_LDAP_Connection,
        Invoicing_Module_Config_WorkOrderStatusForInvoicing,
        Invoicing_Module_Config_WorkOrderStatusForUnPaidInvoice,
        Invoicing_Module_Config_WorkOrderStatusForPaidInvoice,
        Send_WR_Notification_Based_On_Asset_Permission,
        NSC_Customization,
        Service_Report_ImageBannerasheader,
        Issuance_With_Approval,
        Custom_Notifications,
        Service_Report_Templates,
        Enable_Asset_Type,
        Service_Report_ToolsInformation,
        Open_Closed_WorkOrders,
        Additional_Fields,
        Department_Fields,
        Rental_Job,
        AssetTag_ArabicText,
        WOCompletion_Only_When_All_Crews_Complete,
        WOlist_all_assigned_crews,
        Prefix_Rental_Job_Location1,
        Prefix_Rental_Job_Jobs,
        Prefix_Rental_Job_Job_Current_Reference_No,
        Prefix_Rental_Job_Delivery,
        Prefix_Rental_Job_Delivery_Current_Reference_No,
        Rental_Job_Delivery_Pdf_Body,
        Installation_Type,
        Server_URL,
        Server_Company,
        IssuanceExist,
        Enable_PurchaseRequestReport_NewTemplate,
        Description_List,
        SLA_configuration,
        Custom_Services,
        Prefix_Rental_Job_Return,
        Prefix_Rental_Job_Return_Current_Reference_No,
        Rental_Job_Return_Pdf_Body,
        Spare_part_cost_should_be_shown_in_crew_login,
        Job_Equipment_Requirement,
        Non_Inventory_Consumables,
        Calculate_Depreciation,
        Show_Currency_In_PR,
        Show_SalesType_In_PR,
        Add_Batch_Number_To_Asset,
        WorkOrder_Report,
        WorkOrder_Report_Subject,
        Enable_LHC_Integration,
        Service_Report_ShowCustomerAssetId,
        Service_Report_ShowJobOrderInformation,
        Material_Request,
        MaterialRequest_Status_Subject,
        MaterialRequest_Status_Notification,
    }

    public enum OperationType
    {
        View = 1,
        Add = 2,
        Modify = 3,
        Delete = 4
    }

    public enum DeleteCompanyResult
    {
        Deleted,
        HasUsers,
        NotFound
    }
}
