using AutoMapper;
using NiotechoneCQRS.Application.User.Commands.Create;
using NiotechoneCQRS.Application.User.Commands.Update;

namespace NiotechoneCQRS.Application.AutoMapper;

public class AutoMapperProfile : Profile
{
    public AutoMapperProfile()
    {
        CreateMap<CreateUserCommand,Domain.Entities.User>()
             .ForMember(dest => dest.UserId, opt => opt.Ignore()) // Id generated by DB
             .ForMember(dest => dest.PasswordDecrypt, opt => opt.MapFrom(src => string.IsNullOrWhiteSpace(src.Password) ? null : src.Password));

        CreateMap<UpdateUserCommand, Domain.Entities.User>()
            .ForMember(dest => dest.Password,
                       opt => opt.Condition((src, dest, srcMember) => !string.IsNullOrWhiteSpace(srcMember as string)))
            .ForMember(dest => dest.CompanyId,
                       opt => opt.MapFrom(src => src.CompanyId ?? 0)) 
            .ForMember(dest => dest.UserId, opt => opt.MapFrom(src => src.Id));
    }

}